name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PIC_RESOURCE_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: v1.0.0
          body: |
            This is the release body for ljn v1.0.0
          draft: false
          prerelease: false