name: Update Release
on:
  push:
    branches:
      - main
jobs:
  update_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Release ID
        id: get_release_id
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PIC_RESOURCE_TOKEN }}
          script: |
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            const release = releases.find(r => r.tag_name === 'v1.0.0')
            if (release) {
              console.log(`Found release ${release.id}`)
              core.setOutput('release_id', release.id)
            } else {
              console.log('No release found')
              core.setOutput('release_id', '')
            }
      - name: Create or Update Release
        if: steps.get_release_id.outputs.release_id
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PIC_RESOURCE_TOKEN }}
          script: |
            await github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.get_release_id.outputs.release_id }},
              tag_name: 'v1.0.0',
              name: 'v1.0.0',
              body: 'This is the release body for v1.0.0'
            })
        else:
          - name: Create Release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.PIC_RESOURCE_TOKEN }}
            with:
              tag_name: v1.0.0
              release_name: v1.0.0
              body: |
                This is the release body for v1.0.0
              draft: false
              prerelease: false
